[workspace]
resolver = "2"
members = ["day-*"]

[package]
name = "aoc-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
itertools = "0.12.0"
nom = "7.1.3"
